Fix installation tests: compile and run icb_parpack_c.

diff --git a/cmake/tstCMakeInstall.sh.in b/cmake/tstCMakeInstall.sh.in
--- a/cmake/tstCMakeInstall.sh.in
+++ b/cmake/tstCMakeInstall.sh.in
@@ -47,6 +47,7 @@ cp "@PROJECT_SOURCE_DIR@/PARPACK/EXAMPLES/MPI/pdndrv1.f" .
 cp "@PROJECT_SOURCE_DIR@/PARPACK/EXAMPLES/MPI/pdndrv3.f" .
 cp "@PROJECT_SOURCE_DIR@/TESTS/icb_arpack_c.c" .
 cp "@PROJECT_SOURCE_DIR@/TESTS/icb_arpack_cpp.cpp" .
+cp "@PROJECT_SOURCE_DIR@/PARPACK/TESTS/MPI/icb_parpack_c.c" .
 
 echo "cmake_minimum_required(VERSION 3.0)"                               > CMakeLists.txt
 echo ""                                                                 >> CMakeLists.txt
@@ -54,7 +55,7 @@ echo "project(tstCMakeInstall Fortran C CXX)"                           >> CMake
 echo ""                                                                 >> CMakeLists.txt
 echo "find_package(BLAS REQUIRED)"                                      >> CMakeLists.txt
 echo "find_package(LAPACK REQUIRED)"                                    >> CMakeLists.txt
-echo "find_package(MPI REQUIRED COMPONENTS Fortran)"                    >> CMakeLists.txt
+echo "find_package(MPI REQUIRED COMPONENTS Fortran C)"                  >> CMakeLists.txt
 echo "find_package(arpackng REQUIRED)"                                  >> CMakeLists.txt
 echo ""                                                                 >> CMakeLists.txt
 echo "add_executable(dnbdr1 dnband.f dnbdr1.f)"                         >> CMakeLists.txt
@@ -92,6 +93,18 @@ echo "target_include_directories(pdndrv1 INTERFACE ARPACK::ARPACK)"     >> CMake
 echo "target_link_libraries(pdndrv1 ARPACK::ARPACK)"                    >> CMakeLists.txt
 echo "target_include_directories(pdndrv1 INTERFACE PARPACK::PARPACK)"   >> CMakeLists.txt
 echo "target_link_libraries(pdndrv1 PARPACK::PARPACK)"                  >> CMakeLists.txt
+echo ""                                                                     >> CMakeLists.txt
+echo "add_executable(icb_parpack_c icb_parpack_c.c)"                        >> CMakeLists.txt
+echo "target_include_directories(icb_parpack_c INTERFACE BLAS::BLAS)"       >> CMakeLists.txt
+echo "target_link_libraries(icb_parpack_c BLAS::BLAS)"                      >> CMakeLists.txt
+echo "target_include_directories(icb_parpack_c INTERFACE LAPACK::LAPACK)"   >> CMakeLists.txt
+echo "target_link_libraries(icb_parpack_c LAPACK::LAPACK)"                  >> CMakeLists.txt
+echo "target_include_directories(icb_parpack_c INTERFACE MPI::MPI_C)"       >> CMakeLists.txt
+echo "target_link_libraries(icb_parpack_c MPI::MPI_C)"                      >> CMakeLists.txt
+echo "target_include_directories(icb_parpack_c INTERFACE ARPACK::ARPACK)"   >> CMakeLists.txt
+echo "target_link_libraries(icb_parpack_c ARPACK::ARPACK)"                  >> CMakeLists.txt
+echo "target_include_directories(icb_parpack_c INTERFACE PARPACK::PARPACK)" >> CMakeLists.txt
+echo "target_link_libraries(icb_parpack_c PARPACK::PARPACK)"                >> CMakeLists.txt
 echo ""                                                                 >> CMakeLists.txt
 echo "find_package(PkgConfig REQUIRED)"                                 >> CMakeLists.txt
 echo "pkg_check_modules(ARPACK IMPORTED_TARGET REQUIRED arpack${LIBSUFFIX}${ITF64SUFFIX})"   >> CMakeLists.txt
@@ -132,6 +145,18 @@ echo "target_include_directories(pdndrv3 INTERFACE PkgConfig::ARPACK)"  >> CMake
 echo "target_link_libraries(pdndrv3 PkgConfig::ARPACK)"                 >> CMakeLists.txt
 echo "target_include_directories(pdndrv3 INTERFACE PkgConfig::PARPACK)" >> CMakeLists.txt
 echo "target_link_libraries(pdndrv3 PkgConfig::PARPACK)"                >> CMakeLists.txt
+echo ""                                                                           >> CMakeLists.txt
+echo "add_executable(icb_parpack_c_pkg icb_parpack_c.c)"                          >> CMakeLists.txt
+echo "target_include_directories(icb_parpack_c_pkg INTERFACE BLAS::BLAS)"         >> CMakeLists.txt
+echo "target_link_libraries(icb_parpack_c_pkg BLAS::BLAS)"                        >> CMakeLists.txt
+echo "target_include_directories(icb_parpack_c_pkg INTERFACE LAPACK::LAPACK)"     >> CMakeLists.txt
+echo "target_link_libraries(icb_parpack_c_pkg LAPACK::LAPACK)"                    >> CMakeLists.txt
+echo "target_include_directories(icb_parpack_c_pkg INTERFACE MPI::MPI_C)"         >> CMakeLists.txt
+echo "target_link_libraries(icb_parpack_c_pkg MPI::MPI_C)"                        >> CMakeLists.txt
+echo "target_include_directories(icb_parpack_c_pkg INTERFACE PkgConfig::ARPACK)"  >> CMakeLists.txt
+echo "target_link_libraries(icb_parpack_c_pkg PkgConfig::ARPACK)"                 >> CMakeLists.txt
+echo "target_include_directories(icb_parpack_c_pkg INTERFACE PkgConfig::PARPACK)" >> CMakeLists.txt
+echo "target_link_libraries(icb_parpack_c_pkg PkgConfig::PARPACK)"                >> CMakeLists.txt
 
 # 5. Build and test this new project with cmake: for this to be possible, find_package must work.
 
@@ -145,8 +170,10 @@ make all VERBOSE=1 || exit 1
 ./icb_arpack_c || exit 1
 ./icb_arpack_cpp || exit 1
 mpirun -n 2 ./pdndrv1 || exit 1
+mpirun -n 2 ./icb_parpack_c || exit 1
 
 ./dnbdr3 || exit 1
 ./icb_arpack_c_pkg || exit 1
 ./icb_arpack_cpp_pkg || exit 1
 mpirun -n 2 ./pdndrv3 || exit 1
+mpirun -n 2 ./icb_parpack_c_pkg || exit 1
diff --git a/pkg-config/tstAutotoolsInstall.sh.in b/pkg-config/tstAutotoolsInstall.sh.in
--- a/pkg-config/tstAutotoolsInstall.sh.in
+++ b/pkg-config/tstAutotoolsInstall.sh.in
@@ -44,6 +44,7 @@ cp "${PROJECT_SOURCE_DIR}/PARPACK/EXAMPLES/MPI/pdndrv1.f" .
 cp -fr "${PROJECT_SOURCE_DIR}/m4" .
 cp "${PROJECT_SOURCE_DIR}/TESTS/icb_arpack_c.c" .
 cp "${PROJECT_SOURCE_DIR}/TESTS/icb_arpack_cpp.cpp" .
+cp "${PROJECT_SOURCE_DIR}/PARPACK/TESTS/MPI/icb_parpack_c.c" .
 
 echo "AC_PREREQ([2.68])                                                       "  > configure.ac
 echo "AC_INIT([tstAutotoolsInstall], 1.0)                                     " >> configure.ac
@@ -68,6 +69,12 @@ echo "AX_MPI([], AC_MSG_ERROR([could not compile a Fortran MPI test program]))" 
 echo "F77=\$MPIF77                                                            " >> configure.ac
 echo "AC_SUBST([MPI_Fortran_LIBS])                                            " >> configure.ac
 echo "                                                                        " >> configure.ac
+echo "AC_LANG_PUSH([C])                                                       " >> configure.ac
+echo "AX_MPI([], AC_MSG_ERROR([could not compile a C MPI test program]))      " >> configure.ac
+echo "AC_SUBST([MPI_C_LIBS], ["\$MPILIBS \$FCLIBS"])                          " >> configure.ac
+echo "CC=\$MPICC                                                              " >> configure.ac
+echo "AC_LANG_POP([C])                                                        " >> configure.ac
+echo "                                                                        " >> configure.ac
 echo "PKG_CHECK_MODULES([ARPACK], [arpack${LIBSUFFIX}${ITF64SUFFIX}])         " >> configure.ac
 echo "AC_SUBST([ARPACK_CFLAGS])                                               " >> configure.ac
 echo "AC_SUBST([ARPACK_LIBS])                                                 " >> configure.ac
@@ -86,7 +93,7 @@ echo "ACLOCAL_AMFLAGS  = -I m4                                                  
 echo "                                                                                                     " >> Makefile.am
 echo "EXTRA_DIST = debug.h stat.h                                                                          " >> Makefile.am
 echo "                                                                                                     " >> Makefile.am
-echo "bin_PROGRAMS    = dnbdr1 pdndrv1 icb_arpack_c icb_arpack_cpp                                         " >> Makefile.am
+echo "bin_PROGRAMS    = dnbdr1 pdndrv1 icb_arpack_c icb_arpack_cpp icb_parpack_c                           " >> Makefile.am
 echo "                                                                                                     " >> Makefile.am
 echo "dnbdr1_SOURCES = dnbdr1.f dnband.f                                                                   " >> Makefile.am
 echo "dnbdr1_FFLAGS  = \$(ARPACK_CFLAGS)                                                                   " >> Makefile.am
@@ -103,6 +110,10 @@ echo "                                                                          
 echo "icb_arpack_cpp_SOURCES = icb_arpack_cpp.cpp                                                          " >> Makefile.am
 echo "icb_arpack_cpp_CPPFLAGS = \$(ARPACK_CFLAGS)                                                          " >> Makefile.am
 echo "icb_arpack_cpp_LDADD = \$(ARPACK_LIBS) \$(LAPACK_LIBS) \$(BLAS_LIBS)                                 " >> Makefile.am
+echo "                                                                                                     " >> Makefile.am
+echo "icb_parpack_c_SOURCES = icb_parpack_c.c                                                              " >> Makefile.am
+echo "icb_parpack_c_CPPFLAGS = \$(AM_CPPFLAGS) \$(PARPACK_CFLAGS) \$(ARPACK_CFLAGS)                        " >> Makefile.am
+echo "icb_parpack_c_LDADD = \$(PARPACK_LIBS) \$(ARPACK_LIBS) \$(LAPACK_LIBS) \$(BLAS_LIBS) \$(MPI_C_LIBS)  " >> Makefile.am
 
 # 5. Build and test this new project with configure: for this to be possible, PKG_CHECK_MODULES must work.
 
@@ -114,4 +125,6 @@ make all || exit 1
 ./dnbdr1 || exit 1
 ./icb_arpack_c || exit 1
 ./icb_arpack_cpp || exit 1
+
 mpirun -n 2 ./pdndrv1 || exit 1
+mpirun -n 2 ./icb_parpack_c || exit 1
